### ISSUE TITLE
你的那个数据库c3p0-config.xml中哪个是连接mysql的，是上面的default-config 还是下面的named-config

### ISSUE THREAD

**Issue by dellyang** [ztmark/managementsystem#1]
配置文件jdbc:mysql://localhost:3306/mydb
jdbc:mysql://localhost:3306/management_system
这两个哪个是连接mysql的

**Comment by ztmark** [comment]
@dellyang  在`DBUtil`类中的`new ComboPooledDataSource()`表示使用的是default-config，如果想使用另一个配置，可以将配置的名字传到`new ComboPooledDataSource()`构造函数中

**Comment by dellyang** [comment]
谢谢哈
